=== mhomola/AutonomousFlight/conf/gcs/layout.dtd
<!ELEMENT layout (rows|columns|widget)>
<!ELEMENT rows (columns|widget)*>
<!ELEMENT columns (rows|widget)*>
<!ELEMENT widget (papget)*>
<!ELEMENT papget (property)*>
<!ELEMENT property EMPTY>

<!ATTLIST layout
width CDATA #IMPLIED
height CDATA #IMPLIED
>

<!ATTLIST rows
size CDATA #IMPLIED
>

<!ATTLIST columns
size CDATA #IMPLIED
>

<!ATTLIST widget
name CDATA #REQUIRED
size CDATA #IMPLIED
>

<!ATTLIST papget
type CDATA #REQUIRED
x CDATA #REQUIRED
y CDATA #REQUIRED
display CDATA #REQUIRED
>

<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

=== mhomola/AutonomousFlight/conf/gcs/left_col.xml
<!DOCTYPE layout SYSTEM "layout.dtd">

<layout width="1024" height="768">
 <columns>
   <rows size="400">
      <widget size="300" name="strips"/>
<!--      <widget size="300" name="plugin"/> -->
      <widget name="alarms"/>
   </rows>
   <rows>
     <widget name="map2d"/>
     <widget name="aircraft"/>
   </rows>
 </columns>
</layout>

=== mhomola/AutonomousFlight/conf/gcs/alt.xml
<!DOCTYPE layout SYSTEM "layout.dtd">

<layout width="1024" height="768">
 <rows>
  <widget size="400" name="map2d"/>
  <widget size="100" name="altgraph"/>
  <columns>
   <rows size="375">
    <widget size="200" name="strips"/>
   </rows>
   <widget size="400" name="aircraft"/>
   <widget name="alarms"/>
  </columns>
 </rows>
</layout>

=== mhomola/AutonomousFlight/conf/gcs/AGGIEAIR/vertical.xml
<!DOCTYPE layout SYSTEM "../layout.dtd">

<layout width="1855" height="1056">
  <columns>
    <rows SIZE="600">
      <widget NAME="strips" size="225"/>
      <widget NAME="aircraft" size="350"/>
      <widget NAME="alarms" size="467"/>
    </rows>
    <rows>
      <widget NAME="map2d" size="1054">
        <papget type="expression" display="gauge" x="66" y="680">
          <property name="scale" value="1"/>
          <property name="expr" value="(RSSI_COMBINED.remote_rssi-RSSI_COMBINED.remote_noise)"/>
          <property name="min" value="100"/>
          <property name="max" value="250"/>
          <property name="size" value="50."/>
          <property name="text" value="RSSI Remote(dB)"/>
        </papget>
        <papget type="message_field" display="gauge" x="64" y="367">
          <property name="scale" value="1."/>
          <property name="field" value="COPILOT_STATUS:used_disk"/>
          <property name="min" value="0."/>
          <property name="max" value="100."/>
          <property name="size" value="50."/>
          <property name="text" value="Copilot disk(%)"/>
        </papget>
        <papget type="message_field" display="led" x="268" y="46">
          <property name="scale" value="1"/>
          <property name="field" value="CAMERA_PAYLOAD:door_status"/>
          <property name="size" value="15."/>
          <property name="text" value="Door status:"/>
          <property name="test_invert" value="true"/>
        </papget>
        <papget type="message_field" display="text" x="144" y="57">
          <property name="scale" value="1"/>
          <property name="field" value="CAMERA_SNAPSHOT:snapshot_image_number"/>
          <property name="format" value="Capture number: %.0f"/>
          <property name="size" value="15."/>
        </papget>
        <papget type="message_field" display="gauge" x="66" y="464">
          <property name="scale" value="1."/>
          <property name="field" value="COPILOT_STATUS:used_memory"/>
          <property name="min" value="0."/>
          <property name="max" value="100."/>
          <property name="size" value="50."/>
          <property name="text" value="Copilot mem(%)"/>
        </papget>
        <papget type="message_field" display="gauge" x="64" y="272">
          <property name="scale" value="1.0"/>
          <property name="field" value="CAMERA_PAYLOAD:used_memory"/>
          <property name="min" value="0."/>
          <property name="max" value="100."/>
          <property name="size" value="50."/>
          <property name="text" value="Payload mem(%)"/>
        </papget>
        <papget type="expression" display="gauge" x="187" y="681">
          <property name="scale" value="1"/>
          <property name="expr" value="(RSSI_COMBINED.local_rssi-RSSI_COMBINED.local_noise)"/>
          <property name="min" value="100"/>
          <property name="max" value="250"/>
          <property name="size" value="50."/>
          <property name="text" value="RSSI Local(dB)"/>
        </papget>
        <papget type="message_field" display="gauge" x="60" y="176">
          <property name="scale" value="1"/>
          <property name="field" value="CAMERA_PAYLOAD:used_disk"/>
          <property name="min" value="0."/>
          <property name="max" value="100."/>
          <property name="size" value="50."/>
          <property name="text" value="Payload disk(%)"/>
        </papget>
        <papget type="message_field" display="led" x="465" y="22">
          <property name="scale" value="1"/>
          <property name="field" value="CAMERA_PAYLOAD:error_code"/>
          <property name="size" value="15."/>
          <property name="text" value="Payload status:"/>
	  <property name="test_invert" value="true"/>
        </papget>
        <papget type="message_field" display="text" x="478" y="11">
          <property name="scale" value="1"/>
          <property name="field" value="CAMERA_PAYLOAD:error_code"/>
          <property name="format" value="code: %.0f"/>
          <property name="size" value="15."/>
          <property name="color" value="green"/>
        </papget>
        <papget type="message_field" display="text" x="145" y="11">
          <property name="scale" value="1"/>
          <property name="field" value="CAMERA_SNAPSHOT:array_temp"/>
          <property name="format" value="FPA Temp: %.2f"/>
          <property name="size" value="15."/>
          <property name="color" value="blue"/>
        </papget>
      </widget>
    </rows>
  </columns>
</layout>
